name: BetterFlowers
version: '1.0.0'
main: com.uroria.betterflowers.BetterFlowers
api-version: '1.20'
website: https://uroria.com
author: Konfuzius
description: A strong tool to create custom flowers & use them as a brush.

commands:
  flower:
    description: Opens a menu to create custom flower.
  flowerbrush:
      description: Opens a menu to create flower brush.
  uf:
    description: Undo your last placed flower/brush.