name: BetterFlowers
version: '1.0.2'
main: com.uroria.betterflowers.BetterFlowers
api-version: '1.20'
website: https://uroria.com
author: Konfuzius
description: A strong tool to create custom flowers & use them as a brush.

commands:
  flower:
    description: Opens a menu to create custom flower.
    aliases:
      - f
      - F
  flowerbrush:
      description: Opens a menu to create flower brush.
      aliases:
        - fb
        - Fb
        - fB
        - FB
  undoflower:
    description: Undo your last placed flower/brush.
    aliases:
      - uf
      - Uf
      - uF
      - UF